### ISSUE TITLE
Convert Confidential Survey ATO documentation to new format

### ISSUE THREAD

**Issue by DavidEBest** [18F/compliance-toolkit#23]
The new format should also allow the documentation to live in the Confidential Survey repository.
- https://github.com/18F/cg-compliance/pull/33
- https://github.com/18F/cg-compliance#starting-ato-documentation-for-cloudgov-applications

**Comment by afeld** [comment]
We have a new applications using Masonry, so not worth going back to this.

/cc https://github.com/eregs/notice-and-comment/pull/424
